name: CI/CD - Despachos Innovatech

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    name: Build, Push & deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Login en docker hub
        uses: docker/login-actions@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build y push imagen docker
        uses: docker/build-push-actions@v5
        with:
          context: ./Springboot-API-REST-DESPACHO
          dockerfile: ./Springboot-API-REST-DESPACHO/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/despachos-backend:latest

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ir al directorio del proyecto
            cd /home/${{ secrets.EC2_USER }}/despachos-backend

            # Crear archivo .env con las variables de entorno
            echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" > .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

            # Bajar la imagen más reciente
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/despachos-backend:latest

            # Reiniciar solo el servicio app (sin tocar la BD)
            docker compose down app
            docker compose up -d app

            # Limpiar imágenes antiguas
            docker image prune -f